name: Terraform Static Analysis

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to latest version

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2  # Assume v2 is the latest and compatible with Node.js 20

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate
